import React, {Component} from 'react'
import ReactDOM, {render}  from 'react-dom'
import "./index.css"
// import Artos from './components/artos'
// import CoolHeader from './components/header'
// import TodoItem from './components/todoItem'
// import Apex from './components/apex'
// import Footer from './components/footer'
// import Apl from './components/apl'
// // import App from './App'
// import AppClassState from './components/AppClassState'
// import App30 from './components/App30'
import App32 from './components/App32'
// import App from './TODO/App'
//import Artos from './components/artos'
//import CoolHeader from './components/header'
//import TodoItem from './components/todoItem'
//import Apex from './components/apex'
//import Footer from './components/footer'
//import Apl from './components/apl'
//import App from './App'
import Artos from './components/artos'
import CoolHeader from './components/header'
import TodoItem from './components/todoItem'
import Apex from './components/apex'
import Footer from './components/footer'
import Apl from './components/apl'
//import App from './App'
import AppClassState from './components/AppClassState'
import App30 from './components/App30'
import App from './TODO/App'
//import App from './jokes/App'

render(<App32/> ,document.getElementById('root'))